WIP: Update uri-redis version + small fixes
onetimesecret/onetimesecret pull request #427
Opened 2024-06-16 20:29 UTC by sebastien-coavoux

Probably need to rebase on #426 first , or maybe #426 can pick up the diff 
Related to #238

2024-06-17 16:07 UTC, sebastien-coavoux commented
@delano the familia update with the exception raised prevent any boolean field to be stored in redis hashmap. 
This breaks the app from the start (authenticated field for a customer is a boolean) and most of the app itselft later. 

Not sure how you want to handle the serialization of boolean but as of now Familia is not able to write into redis. 
Either we convert any boolean / nil field before writing hasmap or not use boolean in any object that end up in redis 

I pushed another fix but not sure if that covers all

2024-06-17 17:13 UTC, delano commented
> Not sure how you want to handle the serialization of boolean but as of now Familia is not able to write into redis.

Do you mean Familia is not saving any fields correctly or that it's not saving booleans correctly?

> (authenticated field for a customer is a boolean)

I'm going to look at this now and fix. Please let me know of other boolean/nil field issues you find. 

> most of the app itselft later.

Hopefully not most 😅. Raising the exception is the right thing for Familia to do as a library. So it's okay that Onetime Secret needs to be updated -- it's actually improving the codebase as we remove the ambiguity.

2024-06-18 00:15 UTC, sebastien-coavoux commented
> Do you mean Familia is not saving any fields correctly or that it's not saving booleans correctly?
> 

Yes meant the Boolean and nil
> I'm going to look at this now and fix. Please let me know of other boolean/nil field issues you find.
> 
> Hopefully not most 😅. Raising the exception is the right thing for Familia to do as a library. So it's okay that Onetime Secret needs to be updated -- it's actually improving the codebase as we remove the ambiguity.

I tagged you in the commit I did to be more accurate so that we are on the same page. So far the "basic" flow was working (login as "root" -> create a secret -> read it)

I havent played with expiration or password parameter for instance so that might contain boolean / nil

2024-06-18 15:02 UTC, delano requested changes
Thanks for getting these changes into a PR so quick. Really nice find with that OT::Session.create bug. 

With a few changes, we'll be near ready to merge.

2024-06-18 15:02 UTC, delano commented on Dockerfile
> +RUN mkdir -p "$ONETIME_HOME/tmp"
Let's keep the PR focused on the main purpose and remove this and the docker compose file changes. 

```suggestion
RUN mkdir -p "$ONETIME_HOME/{log,tmp}"
```

2024-06-18 15:02 UTC, delano commented on config.ru
> +#Otto.debug = true
Extra doc lines become cruft quickly (even when they're helpful). It's best to keep them out of the codebase from the start. 

```suggestion
```

2024-06-18 15:02 UTC, delano commented on docker-compose.yml
> +      - "cd /src && rm -rf /app/ && cp -r /src /app && cd /app ; exec ./bin/entrypoint.sh"
Couple things here:
- This docker compose config is meant as a starting point. Overriding the entrypoint script with a command is exactly how to customize the startup behaviour. 
- We'll be moving the docker compose config to its own repo soon. That will open the door for more example configurations, rather than just having this single one. It would be great to get your input there when the time comes. 


```suggestion
    entrypoint: ["./bin/entrypoint.sh"]
```

2024-06-18 15:02 UTC, delano commented on docker-compose.yml
> +    # Which is host dependent.
I think this could be related to an open issue with #326 images and icons not showing up properly. I haven't been able to replicate it myself. It would helpful to follow-up on this feedback through that issue. 

```suggestion
```

2024-06-18 15:02 UTC, delano commented on docker-compose.yml
> +      - .:/src
```suggestion
      - .:/app
```

2024-06-18 15:02 UTC, delano commented on lib/onetime/app/helpers.rb
> +        @sess = OT::Session.create req.client_ipaddress, "anon", req.user_agent
Top quality bug fix 👌

2024-06-18 15:02 UTC, delano commented on lib/onetime/models/metadata.rb
> +      update_fields :state => :received, :received => Time.now.utc.to_i, :secret_key => "null"
Let's go with empty strings. Like you mention in your comment, "null" then becomes a *special* string. It's unlikely that we'd ever need to store a literal value of "null" but it's still a potential pitfall.

```suggestion
      update_fields :state => :received, :received => Time.now.utc.to_i, :secret_key => ""
```

2024-06-18 15:02 UTC, delano commented on lib/onetime/models/metadata.rb
> +      update_fields :state => :burned, :burned => Time.now.utc.to_i, :secret_key => "null"
```suggestion
      update_fields :state => :burned, :burned => Time.now.utc.to_i, :secret_key => ""
```

2024-06-18 16:16 UTC, sebastien-coavoux commented
Looking at the failed test, I am wondering if i should copy paste the if v.class I did in familia back to [models.rb](https://github.com/onetimesecret/onetimesecret/pull/427/files#diff-50ea411bf71ca7fa7e75007ce5c4e30dd42906e3c60f8287db9a980f24a5f4d7R152)

```
  ## Can store a one-way, encrypted passphrase               
16   s = Onetime::Secret.new :shared
17   s.update_passphrase 'poop'
18   [s.passphrase_encryption, s.passphrase?('poop')]
19   #=> [1, true]
     !=  ["1", true]
```

2024-06-18 18:25 UTC, delano commented
Sorry for the delay. 

Nice, both of these are simple fixes without further repercussions. 

> Looking at the failed test, I am wondering if i should copy paste the if v.class I did in familia back to [models.rb](https://github.com/onetimesecret/onetimesecret/pull/427/files#diff-50ea411bf71ca7fa7e75007ce5c4e30dd42906e3c60f8287db9a980f24a5f4d7R152)
> 
> ```
>   ## Can store a one-way, encrypted passphrase               
> 16   s = Onetime::Secret.new :shared
> 17   s.update_passphrase 'poop'
> 18   [s.passphrase_encryption, s.passphrase?('poop')]
> 19   #=> [1, true]
>      !=  ["1", true]
> ```

Yeah similar fix here. In `Onetime::Models::Passphrase#update_passphrase`, set the number as a string (`self.passphrase_encryption = "1"`). 

> for this one, not sure. Should the key is a Ruby be symbol and not a String ?
> 
> ```
>  ## Keys don't change with values                           
> 15   @metadata.secret_key = :hihi
> 16   [@metadata.rediskey, @metadata.secret_key, @metadata.all]
> 17   #=> ['metadata:ivfn09cpriklqii1zagw6fc96suh8bp:object', :hihi, {"secret_key"=>"hihi"}]
>      !=  ["metadata:ivfn09cpriklqii1zagw6fc96suh8bp:object", "hihi", {"secret_key"=>"hihi"}]
> ```

This one is a just a poorly written test. No where else in the codebase sets `secret_key` to a symbol. It's all strings. It's a rare case where updating the failing test expectation is the right thing to do 👍

2024-06-18 18:59 UTC, delano approved these changes
Good work 👌

2024-06-19 00:11 UTC, sebastien-coavoux commented
Test fixed accordingly

2024-06-19 04:03 UTC, delano approved these changes
Success 😺

2024-06-19 04:04 UTC, merged